

apiVersion: v1
kind: PersistentVolume
metadata:
  name: efk-pv-volume
  labels:
    app: elasticsearch
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"


